"""create initial tables

Revision ID: 9384f3370321
Revises:
Create Date: 2026-03-23 21:44:37.159050

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9384f3370321"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_sports_id"), "sports", ["id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("official_name", sa.String(length=200), nullable=True),
        sa.Column("abbreviation", sa.String(length=10), nullable=True),
        sa.Column("country_code", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=False)
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venues_id"), "venues", ["id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("_sport_id", sa.Integer(), nullable=False),
        sa.Column("_home_team_id", sa.Integer(), nullable=True),
        sa.Column("_away_team_id", sa.Integer(), nullable=True),
        sa.Column("_venue_id", sa.Integer(), nullable=True),
        sa.Column("_competition_id", sa.String(length=100), nullable=True),
        sa.Column("date_venue", sa.Date(), nullable=False),
        sa.Column("time_venue_utc", sa.Time(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("stage_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["_away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["_competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["_home_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["_sport_id"],
            ["sports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["_venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_table(
        "results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("_event_id", sa.Integer(), nullable=False),
        sa.Column("home_goals", sa.Integer(), nullable=True),
        sa.Column("away_goals", sa.Integer(), nullable=True),
        sa.Column("winner", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["_event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("_event_id"),
    )
    op.create_index(op.f("ix_results_id"), "results", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_results_id"), table_name="results")
    op.drop_table("results")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_venues_id"), table_name="venues")
    op.drop_table("venues")
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_sports_id"), table_name="sports")
    op.drop_table("sports")
    op.drop_table("competitions")
    # ### end Alembic commands ###
